jaffle_shop:
  outputs:
    dev:
      account: izyinso-gf41123
      database: RAW
      password: @Debugger12
      role: ACCOUNTADMIN
      schema: JAFFLE_SHOP
      threads: 4
      type: snowflake
      user: squezada
      warehouse: COMPUTE_WH
  target: dev